### ISSUE TITLE
Stats on fastq files

### ISSUE THREAD

**Issue by sr320** [mfisher5/mf-fish546-2016#4]
This might be helpful...
https://github.com/stephenturner/oneliners/blob/40943e6cd4695f3c4d8a1b8d5e940b957e060c26/README.md#awk--sed-for-bioinformatics

the command for 
>Basic sequence statistics. Print total number of reads, total number unique reads, percentage of unique reads, most abundant sequence, its frequency, and percentage of total in file.fq:

```
cat myfile.fq | awk '((NR-2)%4==0){read=$1;total++;count[read]++}END{for(read in count){if(!max||count[read]>max) {max=count[read];maxRead=read};if(count[read]==1){unique++}};print total,unique,unique*100/total,maxRead,count[maxRead],count[maxRead]*100/total}'
```

**Comment by mfisher5** [comment]
This is great, thanks! Also, Jupyter seems to be running fine using %%bash.
